server:
  port: 8081
token:
  secret: 'kajEgkbpCZKICOkuraCEB855q2WUc9AVqIkemL3V0Dm9Ezj4UajzJ3g18Hg7mCvY'
spring:
  application:
    name: asignacion-redis
  redis:
    host: localhost
    #host: redis
    port: 6379
  cloud:
    function:
      definition: publishingDestinationEvent;publishingPointOfSaleEvent;processorResultPointOfSale;processorResultDestination
    stream:
      default-binder: kafka
      default:
        producer:
          useNativeEncoding: true
      bindings:
        event-point:
          destination: redis-point-events
        event-destination:
          destination: redis-destination-events
        processorResultDestination-in-0:
          destination: mongo-result-destination-events
          group: mongo-destination-group
        processorResultPointOfSale-in-0:
          destination: mongo-result-point-events
          group: mongo-point-group
      kafka:
        binder:
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "enable.auto.commit": false
            "spring.json.trusted.packages": "*"
          producer-properties:
            "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer
          brokers: localhost:9092